version: '2'
services:
  ipsc-mongodb: 
    image: mongo:latest
    restart: always
    container_name: ipsc-mongodb
    mem_limit: 4G
    environment:
      MONGO_INITDB_ROOT_USERNAME : ipsc
      MONGO_INITDB_ROOT_PASSWORD : ipasdfb14235346jsbcfdhasbf3q234sc
      MONGO_INITDB_DATABASE : shooting
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/logs/mongo:/data/log
    ports:
      - 27018:27017
      
    command: mongod --logpath=/data/log/mongo.log --smallfiles  --storageEngine=wiredTiger --wiredTigerCacheSizeGB=2
    
  ipsc: 
    container_name: ipsc
    image: shooting.azurecr.io/ipsc:0.2-latest
    volumes:
      - ./data/logs/ipsc:/usr/share/servers/ipsc/logs
      - static-content:/usr/share/servers/ipsc-frontend  
    expose:
      - 9901
    ports:
      - 9901:9901
    depends_on: 
      - ipsc-mongodb     
  ipsc-nginx:
    container_name: ipsc-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ipsc:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx:/var/log/nginx
      - static-content:/usr/share/servers/ipsc-frontend  
    depends_on: 
      - ipsc
      
volumes: 
  static-content: 