version: '3'
services: 
  ipsc: 
    container_name: ipsc
    image: shooting.azurecr.io/ipsc:0.2-latest
    restart: always
    volumes:
      - ./logs:/usr/share/servers/ipsc/logs
    ports:
      - 192.168.0.10:80:9901
      - 192.168.0.10:8808:8808
      - 192.168.0.10:1885:1885