version: '3'
services: 
  ipsc: 
    container_name: ipsc
    image: shooting.azurecr.io/ipsc:0.2-latest
    restart: always
    volumes:
      - ./logs:/usr/share/servers/ipsc/logs
    ports:
      - 80:9901
      - 8880:8880