spring:
  profiles:
    active: local
# Global configuration
---
spring:
  main:
    banner-mode: "off"

server:
  address: 127.0.0.1
  port: 8130

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#management:
#  security:
#    enabled: false

---
spring:
  profiles: local
  main:
    banner-mode: "off"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27018
      database: shooting
      #      authentication-database: admin
      username: ipsc
      password: ipasdfb14235346jsbcfdhasbf3q234sc
server:
  address: 127.0.0.1
  port: 9900
#  http2:
#    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

ipsc:
  mqtt:
    adminLogin: ipsc
    adminpassword: ip2342354dsdsnkjqsc
    ipscTopicName: ipsc
    
---
spring:
  profiles: development
  main:
    banner-mode: "off"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: 40.69.138.82
      port: 27017
      database: shooting
      #      authentication-database: admin
      username: ipsc
      password: ipasdfb14235346jsbcfdhasbf3q234sc
server:
  address: 10.0.6.4
  port: 9901
#  http2:
#    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  connection-timeout: 20000
ipsc:
  mqtt:
    adminLogin: ipsc
    adminpassword: ip2342354dsdsnkjqsc
    ipscTopicName: ipsc
    
---
spring:
  profiles: docker
  main:
    banner-mode: "off"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      #      host: ipsc-mongodb
      host: ipsc-mongodb
      port: 27017
      database: shooting
      authentication-database: admin
      username: ipsc
      password: ipasdfb14235346jsbcfdhasbf3q234sc
server:
  address: 127.0.0.1
  port: 9901
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  connection-timeout: 20000
ipsc:
  mqtt:
    adminLogin: ipsc
    adminpassword: ip2342354dsdsnkjqsc
    ipscTopicName: ipsc
