package tech.shooting.ipsc.enums;

public enum EventTypeEnum {
	COMPETITION_UPDATED, MQTT_CONNECT, MQTT_CONNECTION_LOST, MQTT_DISCONNECT, TEST_STARTED, TAG_DETECTED, TAG_UNDETECTED, RUNNING_UPDATED
}
