package tech.shooting.ipsc.enums;

public enum EventTypeEnum {
	COMPETITION_UPDATED, MQTT_CONNECT, MQTT_CONNECTION_LOST, MQTT_DISCONNECT, WORKSPACE_CHANGED, TEST_STARTED, TEST_FINISHED ,TAG_DETECTED, TAG_UNDETECTED, RUNNING_UPDATED, RUNNING_CONNECT, RUNNING_DISCONNECT
}
