spring:
  profiles:
    active: local
# Global configuration
---
spring:
  main:
    banner-mode: "off"

server:
  address: 127.0.0.1
  port: 8130

---
spring:
  profiles: local
  main:
    banner-mode: "off"
server:
  address: 127.0.0.1
  port: 80

ipsc:
  mqtt:
    adminLogin: ipsc
    adminPassword: ip2342354dsdsnkjqsc
    ipscTopicName: ipsc

---
spring:
  profiles: production
  main:
    banner-mode: "off"
server:
  address: 192.168.0.20
  port: 80
ipsc:
  mqtt:
    adminLogin: ipsc
    adminPassword: ip2342354dsdsnkjqsc
    ipscTopicName: ipsc
