# https://hub.docker.com/r/bitnami/mongodb/dockerfile 

version: '2'
services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    container_name: mongodb
    mem_limit: 2G
    environment:
      MONGODB_USERNAME : "ipsc"
      MONGODB_PASSWORD : "ipasdfb14235346jsbcfdhasbf3q234sc"
      MONGODB_DATABASE : "shooting"
      MONGODB_PORT_NUMBER : 27017
      MONGODB_EXTRA_FLAGS : --logpath=/data/log/mongo.log --smallfiles  --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
    volumes:
#    - ./../data/mongo/db:/data/db
    - ./../data/mongo/log:/data/log
    ports:
    - 27018:27017