# https://hub.docker.com/r/bitnami/mongodb/dockerfile 

version: '3.3'
services: 
  mongodb-primary:
    image: bitnami/mongodb:latest
#    restart: always
#    mem_limit: 8G
    environment:
      MONGODB_USERNAME: ipsc
      MONGODB_PASSWORD: ipasdfb14235346jsbcfdhasbf3q234sc
      MONGODB_DATABASE: shooting
      MONGODB_PORT_NUMBER: 27017
      MONGODB_EXTRA_FLAGS: --smallfiles --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
      
      MONGODB_REPLICA_SET_NAME: replicaset
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: password123 
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      
      NAMI_DEBUG: 1
      
#      MONGODB_PRIMARY_HOST: 127.0.0.1
#      MONGODB_PRIMARY_PORT_NUMBER: 27018
      
#    volumes:
#      - './data/mongodb_master_data:/bitnami'
    ports:
      - 27000:27017