version: '2'
services:
  ipsc-backend:
    container_name: ipsc-backend
    image: docker.mpsdevelopment.com/shooting/ipsc:0.1-latest
    depends_on: 
      - ipsc-mongodb
    volumes:
      - ./data/logs:/usr/share/servers/ipsc/logs
    ports:
      - 9901:9901    
  ipsc-mongodb: 
    image: mongo:latest
    restart: always
    container_name: ipsc-mongodb
    mem_limit: 2G
    environment:
      MONGO_INITDB_ROOT_USERNAME : ipsc
      MONGO_INITDB_ROOT_PASSWORD : ipasdfb14235346jsbcfdhasbf3q234sc
      MONGO_INITDB_DATABASE : shooting
    volumes:
      - ./data/logs:/data/log
    ports:
      - 27018:27017
    command: mongod --logpath=/data/log/mongo.log --smallfiles  --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1
