version: '2'
services:
  rabbit1:
    image: rabbitmq:3-management
    container_name: ipsc-rabbitmq
    restart: always
    hostname: ipsc-rabbitmq
    mem_limit: 1G
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: ip34fdsfdasfdsbgsc
      RABBITMQ_DEFAULT_PASS: iprewgbqw43283yausdhasvfassc
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
      - "1884:1883"
    labels:
      NAME: "ipsc-rabbitmq"
    volumes:
      - ./log:/var/log/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
