version: '2'
services:
  rabbit1:
    image: rabbitmq:3-management
    restart: always
    hostname: "ipsc-rabbitmq"
    mem_limit: 1G
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "ip34fdsfdasfdsbgsc"
      RABBITMQ_DEFAULT_PASS: "iprewgbqw43283yausdhasvfassc"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    labels:
      NAME: "ipsc-rabbitmq"
    volumes:
      - ./log:/var/log/rabbitmq
      - ./rabbitmq:/etc/rabbitmq
