version: '2'
services:
  ipsc-mongodb: 
    image: mongo:4.0.10
    restart: always
    container_name: ipsc-mongodb
    mem_limit: 4G
    environment:
      MONGO_INITDB_ROOT_USERNAME : ipsc
      MONGO_INITDB_ROOT_PASSWORD : ipasdfb14235346jsbcfdhasbf3q234sc
      MONGO_INITDB_DATABASE : shooting
    volumes:
      - ./db:/data/db
      - ./logs:/data/log
    ports:
      - 27018:27017
    command: mongod --logpath=/data/log/mongo.log --smallfiles  --storageEngine=wiredTiger --wiredTigerCacheSizeGB=2